config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    resources :books
  end

  resources :books do
    resources :chapters
  end

  resources :chapters do
    resources :topics
  end

  resources :topics do
    resources :sub_topics
  end

  resources :sub_topics

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book
  validates :book_id, presence: true
  has_many :topics, dependent: :destroy
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    book = Book.find(chapter_params[:book_id])
    @chapter = book.chapters.build(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :description, :book_id)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_for(chapter) do |f| %>
  <% if chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.hidden_field :book_id, value: params[:book_id] %>
<!--   <div class="field">
    <%#= f.label :book_id %>
    <%#= f.select :book_id, options_for_select(Book.all.collect{ |b| [b.title, b.id] }, chapter.book_id) %>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chapters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.title %></td>
        <td><%= chapter.description %></td>
        <td><%= chapter.book.title %></td>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Chapter', new_chapter_path %>

app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chapter.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @chapter.description %>
</p>

<p>
  <strong>Book:</strong>
  <%= @chapter.book.title %>
</p>

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>

<br><br>

<% if @chapter.topics.any? %>
  <h3><%= @chapter.title %> Topics</h3>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @chapter.topics.each do |topic| %>
        <tr>
          <td><%= topic.title %></td>
          <td><%= link_to 'Show', topic %></td>
          <td><%= link_to 'Edit', edit_chapter_topic_path(topic.chapter, topic) %></td>
          <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br><br>

<%= link_to 'New Topic', new_chapter_topic_path(@chapter.id) %>